// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt0pmah6IEFsXkJWcSV_090zaYR0UK9II',
    appId: '1:905091455864:web:5d2eeb799f42efcd5c068d',
    messagingSenderId: '905091455864',
    projectId: 'lafda-fa2ec',
    authDomain: 'lafda-fa2ec.firebaseapp.com',
    storageBucket: 'lafda-fa2ec.appspot.com',
    measurementId: 'G-LFQCFKK341',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZKIAAIk3JGWgLUn20ox_CxbSThDL5GY',
    appId: '1:905091455864:android:5b4cc43a50fe18775c068d',
    messagingSenderId: '905091455864',
    projectId: 'lafda-fa2ec',
    storageBucket: 'lafda-fa2ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7sTeUqvtooy-Zo8U_eZhjFGmSdF7txLA',
    appId: '1:905091455864:ios:20c16da49079c2a35c068d',
    messagingSenderId: '905091455864',
    projectId: 'lafda-fa2ec',
    storageBucket: 'lafda-fa2ec.appspot.com',
    iosBundleId: 'com.example.lafda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7sTeUqvtooy-Zo8U_eZhjFGmSdF7txLA',
    appId: '1:905091455864:ios:2d2529788e667b365c068d',
    messagingSenderId: '905091455864',
    projectId: 'lafda-fa2ec',
    storageBucket: 'lafda-fa2ec.appspot.com',
    iosBundleId: 'com.example.lafda.RunnerTests',
  );
}
